### ISSUE TITLE
Arborescence

### ISSUE THREAD

**Issue by AilfeLirik** [HisteriaMC/HisteriaPack#102]
Organiser les textures d'item de la manière suivante :
![image](https://github.com/HisteriaMC/HisteriaPack/assets/95536716/9f4582ef-9d36-4896-b61f-8d1b6857ba73)

**Comment by dadodasyra** [comment]
ça risque de créer beaucouppp de conflits mais okep, à faire à la fin, par toi si possible, et sans oublier de changer les fichiers de chemins de textures, et les chemins coté plugins aussi
