### ISSUE TITLE
Overlapping dans le scoreboard

### ISSUE THREAD

**Issue by dadodasyra** [HisteriaMC/HisteriaPack#122]
Les effets et le scoreboard se superposent
![image](https://github.com/HisteriaMC/HisteriaPack/assets/44753923/b5873996-3367-402a-bf98-7e6d001305c6)
![image](https://github.com/HisteriaMC/HisteriaPack/assets/44753923/95b8ede6-b00c-46a8-b569-78d518d90c1b)

**Comment by HARYA301** [comment]
Alors ça par contre eeeeeeeh je ne saurais pas comment fix ça
Sans doute un problème de layer

**Comment by dadodasyra** [comment]
> Alors ça par contre eeeeeeeh je ne saurais pas comment fix ça Sans doute un problème de layer

inspire toi...
