### ISSUE TITLE
Clé boss

### ISSUE THREAD

**Issue by zelytra** [HisteriaMC/HisteriaPack#14]

**Comment by AilfeLirik** [comment]
![image](https://github.com/HisteriaMC/HisteriaPack/assets/95536716/95d89dc5-f068-4abe-93f8-6a846798b019)

**Comment by AilfeLirik** [comment]
Une nouvelle clée dans le style de celles qui sont déja implémentées mais cette clée doit néanmoins se démarquer du tas;
Pour te donner de l'inspiration, elle doit donner l'air "puissante", tu peux combiner hist et noc avec un style boss, et elle donneras accès à des objets à usage unique pétés
