### ISSUE TITLE
Boutons de menu

### ISSUE THREAD

**Issue by zelytra** [HisteriaMC/HisteriaPack#16]

**Comment by AilfeLirik** [comment]
modif les boutons du menu pause pour add une fiche simplifiée des rules et une fiche pour la boutique également.
Ci-dessous un exemple;
![image](https://github.com/HisteriaMC/HisteriaPack/assets/95536716/597c1ecb-7cea-435c-9233-e6f2bed30015)

Image simplifiée

![image](https://github.com/HisteriaMC/HisteriaPack/assets/95536716/5e36dbf9-a64c-44e2-92c8-0f2e3cb75c79)

**Comment by HARYA301** [comment]
ça par contre j'en ai aucune idée de comment ça fonctionne en JSON.
Je poursuis les testes plus tard.
