### ISSUE TITLE
Block Magma

### ISSUE THREAD

**Issue by SwouitAzia** [HisteriaMC/HisteriaPack#165]
Bloc de magma, soit custom block soit bind histeria:event_magma sur la texture vanilla.
histeria:event_magma

**Comment by dadodasyra** [comment]
Dans tout les cas c un custom block mais pas forcement de texture quoi

**Comment by HARYA301** [comment]
Issue vraiment pas nécessaire sachant que c'est à vous d'implémenter la bloc custom et de lui appliqué la texture Vanilla

**Comment by SwouitAzia** [comment]
yep, suffit juste de le préciser dans le blocks_texture.json

**Comment by dadodasyra** [comment]
> Issue vraiment pas nécessaire sachant que c'est à vous d'implémenter la bloc custom et de lui appliqué la texture Vanilla

À toi d'indiquer le chmein

**Comment by HARYA301** [comment]
> > Issue vraiment pas nécessaire sachant que c'est à vous d'implémenter la bloc custom et de lui appliqué la texture Vanilla
> 
> À toi d'indiquer le chmein

Mais dans quel but? Vous reprenez le chemin Vanilla donc pas besoin de plus
