### ISSUE TITLE
Changement de texture du Drawer

### ISSUE THREAD

**Issue by HARYA301** [HisteriaMC/HisteriaPack#175]
L'actuel ne ressemble absolument pas à un drawer et les détails sont mal interprété

**Comment by dadodasyra** [comment]
![image](https://github.com/HisteriaMC/HisteriaPack/assets/44753923/18a91bc4-1840-4499-ad27-4e21b563112d)

**Comment by SwouitAzia** [comment]
Niveau 1 : texture simple / 1 tiroir
Niveau 2 : 2 tiroirs
Niveau 3 : 4 tiroirs
Niveau 4 : 7 tiroirs
Niveau 5 : 13 tiroirs

**Comment by HARYA301** [comment]
![image](https://github.com/HisteriaMC/HisteriaPack/assets/57374230/f19aac46-22b3-4ee9-9381-dff28590a196)

**Comment by HARYA301** [comment]
4 tiroirs ça commence à être la merde alors imaginez pas avec 12

**Comment by SwouitAzia** [comment]
pas de problème, fais x tiroirs pour x niveau d'amélioration. 7-13 laisse tomber
