### ISSUE TITLE
magma block sans nom 

### ISSUE THREAD

**Issue by Zeleph1111** [HisteriaMC/HisteriaPack#176]
![image](https://github.com/HisteriaMC/HisteriaPack/assets/114947889/9f7f469b-e1f4-45e9-b01d-5e73febecef8)

**Comment by HARYA301** [comment]
Je suis d'accord

**Comment by Tonmou8128** [comment]
Je précise que le bloc est obtensible pour les joueurs & qu'il a un nom correct
![Screenshot_2024-01-12-13-32-45-54_5c8300b655012b1930f2e0a7b81bf6a9](https://github.com/HisteriaMC/HisteriaPack/assets/149319443/77f70810-2559-4152-8de3-07181d42f211)

**Comment by Tonmou8128** [comment]
Ah j'ai mal vu c'est pas le même sorry
