### ISSUE TITLE
Fix rendus 3D items des boss

### ISSUE THREAD

**Issue by zelytra** [HisteriaMC/HisteriaPack#20]

**Comment by AilfeLirik** [comment]
Problème avec le rendu 3D de la lance et du sceptre; screen ci-joints
![image](https://github.com/HisteriaMC/HisteriaPack/assets/95536716/94b26015-628f-4588-b78b-2a7a6b00ff35)
![image](https://github.com/HisteriaMC/HisteriaPack/assets/95536716/5ed89018-b280-44b7-9ed6-dd5f4bc67e46)

(La lance est dans mon cul)

**Comment by HARYA301** [comment]
Je suis en train de travailler sur un fix en testant via un behaviour pack
C'est très chiant, très chiant

**Comment by HARYA301** [comment]
Alors les résultats que j'ai eu avec les tests ne sont pas positifs, je vais essayer mon max mais Ailfe je suis désolé si c'est possible
