### ISSUE TITLE
Model snow shovel

### ISSUE THREAD

**Issue by SwouitAzia** [HisteriaMC/HisteriaPack#213]
Pelle à neige
Nom / ID de l’item : snow_shovel / histeria:snow_shovel
Nom en français : Pelle à neige
Description : pelle en histerite avec un peu de neige au dessus.

**Comment by dadodasyra** [comment]
comment ça model ?

**Comment by dadodasyra** [comment]
> > comment ça model ?
> 
> c'est pour afficher l'équipement dans une vitrine en prémices à l'évènement.

tu fais tout simplement une item stasis. Un truc ou l'item est drop et irrécupérable
