### ISSUE TITLE
Largage/airdrop

### ISSUE THREAD

**Issue by dadodasyra** [HisteriaMC/HisteriaPack#239]
On a besoin d'une entité avec balon + caisse, et un block avec juste la caisse:
histeria:air_drop pour entité et block
le model proposé par "maz mais selon moi à modifier
![image](https://github.com/user-attachments/assets/76abda03-b367-4f6d-bbb6-c22b24aceec7)
https://drive.histeria.fr/f/a7d364cdd77244e6adff/

**Comment by HARYA301** [comment]
Okay ça marche
Ouais je vais le modifier parce que bon. ENfin bref

**Comment by HARYA301** [comment]
Une colorie désiré ou pas?

**Comment by dadodasyra** [comment]
non
