### ISSUE TITLE
BC - Mixed Sand

### ISSUE THREAD

**Issue by AilfeLirik** [HisteriaMC/HisteriaPack#244]
un sable résistant aux explosions et peu onéreux (protection entre obsidian vanilla et obsi tier hist)
 
 Côté texture du gravier/sable mixé avec de l'hist (tu peux faire qu'avec du sable c'est comme tu veux)

**Comment by HARYA301** [comment]
Le craft c'est du sable et du gravier mélangé?

**Comment by AilfeLirik** [comment]
c'est sable/gravier mxié avec de l'hist, un mix de tout en gros
