### ISSUE TITLE
Punching Ball

### ISSUE THREAD

**Issue by AilfeLirik** [HisteriaMC/HisteriaPack#53]
Refonte texture.

**Comment by HARYA301** [comment]
J'avais fait un model pour le punshing ball. Vous le prennez aussi ou pas? La texture de l'item va avec

**Comment by AilfeLirik** [comment]
Oui mais pense bien à faire une animation de coup subis et une animation de destruction

**Comment by HARYA301** [comment]
> Oui mais pense bien à faire une animation de coup subis et une animation de destruction

ça marche je vais voir ça, par contre je ne sais pas comment faire une animation où elle est uniquement jouer en fonction d'où le joueur est positionné
