### ISSUE TITLE
Implémentation scoreboard

### ISSUE THREAD

**Issue by dadodasyra** [HisteriaMC/HisteriaPack#82]
Déjà fait mais pas de pr pour

**Comment by zelytra** [comment]
Il faut préciser le besoin

**Comment by dadodasyra** [comment]
Il sait ce qu'il a déjà fait et pas moi, c'est du code json de la magie mojangesque

**Comment by zelytra** [comment]
Non, je te demande d'exprimer ton besoins. Ce que tu veux TOI. Que dois faire Haragon (meme si c'est deja fait, ca permet de confirmer ce qu'as fait haragon est bon et conforme aux exigences)

**Comment by dadodasyra** [comment]
C'est compliqué et avait été géré par ailfe

**Comment by zelytra** [comment]
Si c'est compliquer ca l'est encore plus pour haragon. Donc il faudrais exprimer un besoins claire et poser ce que vous voulez. Si c'est mal fait ca seras votre probleme pas le siens et je serais de son coter

**Comment by dadodasyra** [comment]
Mais il sait exactement a quoi ca correspond pls

**Comment by AilfeLirik** [comment]
Seul soucis qu'on a c'est que les textes qui bridés au bout du scoreboard, dès que le texte est long il est remplacé par "..."
